FROM node:14.16.1-alpine

# Set working directory
WORKDIR /app

# Copy project files to working directory
COPY . .

# Install Python
RUN apk update && \
    apk add --no-cache python3 make g++

ENV API_URL http://backend-service

# Install dependencies
RUN yarn install

# Build the application
RUN yarn build

# Set the container to listen on port 3000
EXPOSE 3000

# Start the Nuxt.js application
CMD yarn dev --hostname 0.0.0.0

