resources: 
- resume_frontend.yml
- resume_backend.yml
- db.yml

configMapGenerator: 
- name: laravel-config
  files:
  - .env 

patches:
- target:
    kind: Deployment
    name: frontend
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom
      value:
      - configMapRef:
          name: laravel-config
- target:
    kind: Deployment
    name: db
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom
      value:
      - configMapRef:
          name: laravel-config