apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  .env: |
    APP_NAME=Laranuxt
    APP_ENV=local
    APP_KEY=
    APP_DEBUG=true
    APP_URL=http://frontend-service
    API_URL=http://backend-service:80
    WEB_URL=http://frontend-service:80
    IGNITION_THEME=dark

    LOG_CHANNEL=stack

    DB_CONNECTION=mysql
    DB_HOST=db-service
    DB_PORT=3306
    DB_DATABASE=resumeBuilder
    DB_USERNAME=root
    DB_PASSWORD=

    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120

    AWS_ACCESS_KEY_ID=
    AWS_SECRET_ACCESS_KEY=
    AWS_DEFAULT_REGION=us-east-1
    AWS_BUCKET=

    PUSHER_APP_ID=
    PUSHER_APP_KEY=
    PUSHER_APP_SECRET=
    PUSHER_APP_CLUSTER=mt1
